name: Tokyo Flight Deals

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * 0"

jobs:
  check-flights:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r tokyo-flight-deals/requirements.txt

      - name: Check flights
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          cd tokyo-flight-deals
          python main.py
